apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - odf-operator-app.yaml
  - odf-storagecluster-appset.yaml
  - elasticsearch-operator-app.yaml
  - elasticsearch-instance-appset.yaml
  - grafana-operator-app.yaml
  - grafana-instance-appset.yaml
