apiVersion: v1
baseDomain: xxxx.xxx.xxx
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    azure:
      type: Standard_D8s_v6
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      type: Standard_D8s_v6
  replicas: 3
metadata:
  creationTimestamp: null
  name: demo
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/21
    hostPrefix: 24
  - cidr: 10.130.0.0/21
    hostPrefix: 24
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: xxxxxxx
    cloudName: AzurePublicCloud
    outboundType: Loadbalancer
    region: eastus
publish: External
#pullSecret: '#redacted'
#sshKey: |
#  redacted
