apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cnv
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    # Allow Subscription/HCO nodePlacement to override the project default selector
    openshift.io/node-selector: ""
